const EVENTS = {
  CORPORATE_RETREATS: "corporate retreats",
  MEDIEVAL_FAIRS: "medieval fairs",
  GALA_DINNERS: "gala dinners",
  ART_EXHIBITIONS: "art exhibitions",
  MUSIC_CONCERTS: "music concerts",
  WRITING_RETREATS: "writing retreats",
  WELLNESS_RETREATS: "wellness retreats",
  YOGA_SESSIONS: "yoga sessions",
  COOKING_CLASSES: "cooking classes",
  THEMED_PARTIES: "themed parties",
  VIP_EVENTS: "vip events",
  CASTLE_BALLS: "castle balls",
  GHOST_HUNTING: "ghost hunting",
  MEDIEVAL_FEASTS: "medieval feasts",
  HISTORICAL_REENACTMENTS: "historical reenactments",
  NIGHT_TOURS: "torch-lit night tours",
  WINE_TASTING: "wine tasting events",
  GARDEN_PARTIES: "garden parties",
  COSTUME_BALLS: "costume balls",
  LITERARY_READINGS: "literary readings",
  THEMED_BANQUETS: "themed banquets",
};

export default EVENTS;
